version: '3.8'

services:
  docker:
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay2
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_docker_certs:/certs/client

  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_home:
    # external: true
  jenkins_docker_certs:
    driver: local
